FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# bandDB API

bandDB is an API for viewing bands data, including band members, member infomation, 
genre, albums, tours and songs.


## Artists [/artists/{id}{?query1,query2}]

+ Parameters
    + id - A path variable that is required for a valid URL
    + query1 (optional) - A query variable
    + query2 (optional) - Another query variable

### List all artists [GET]
+ Response 204

### Post a new artist [POST]
+ Request (application/json)

+ Response 201 


## Albums [/albums/{id}{?query1,query2}]

+ Parameters
    + id - Path variable
    + query1 (optional) - Query variable
    + query2 (optional) - Query variable

### List all albums [GET]
+ Response 204

### Post a new album [POST]
+ Request (application/json)

+ Response 201 (application/json)


## Tours [/tours/{id}{?query1,query2}]
+ Parameters
    + id - Path variable
    + query1 (optional) - Query variable
    + query2 (optional) - Query variable

### List all tours [GET]
+ Response 204

### Post a new tour [POST]
+ Request (application/json)

+ Response 201 (application/json)


## Songs [/songs/{id}{?query1,query2}]
+ Parameters
    + id - Path variable
    + query1 (optional) - Query variable
    + query2 (optional) - Query variable



### List all songs [GET]

+ Response 204


### Post a new song [POST]

+ Request (application/json)

+ Response 204